/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetSenhaRouteImport } from './routes/reset-senha'
import { Route as PortalMembroRouteImport } from './routes/portal-membro'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AcessoNegadoRouteImport } from './routes/acesso-negado'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as PortalMembroSubstituicoesRouteImport } from './routes/portal-membro/substituicoes'
import { Route as PortalMembroRankingRouteImport } from './routes/portal-membro/ranking'
import { Route as PortalMembroPerfilRouteImport } from './routes/portal-membro/perfil'
import { Route as PortalMembroOcorrenciasRouteImport } from './routes/portal-membro/ocorrencias'
import { Route as PortalMembroNotificacoesRouteImport } from './routes/portal-membro/notificacoes'
import { Route as PortalMembroLiturgiaRouteImport } from './routes/portal-membro/liturgia'
import { Route as PortalMembroHomeRouteImport } from './routes/portal-membro/home'
import { Route as PortalMembroEventosRouteImport } from './routes/portal-membro/eventos'
import { Route as PortalMembroEscalasRouteImport } from './routes/portal-membro/escalas'
import { Route as PortalMembroCompletarCadastroRouteImport } from './routes/portal-membro/completar-cadastro'
import { Route as PortalMembroCalendarioRouteImport } from './routes/portal-membro/calendario'
import { Route as PortalMembroAjudaRouteImport } from './routes/portal-membro/ajuda'
import { Route as ParoquiaSlugRouteImport } from './routes/paroquia.$slug'
import { Route as MembroPrimeiroAcessoRouteImport } from './routes/membro/primeiro-acesso'
import { Route as MembroLoginRouteImport } from './routes/membro/login'
import { Route as MembroAtivarContaRouteImport } from './routes/membro/ativar-conta'
import { Route as MembroTokenRouteImport } from './routes/membro.$token'
import { Route as InscricaoSlugRouteImport } from './routes/inscricao.$slug'
import { Route as EscalaTokenRouteImport } from './routes/escala.$token'
import { Route as AuthMfaChallengeRouteImport } from './routes/auth.mfa-challenge'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthAdminMfaRouteImport } from './routes/auth.admin-mfa'
import { Route as AuthenticatedSubstituicoesRouteImport } from './routes/_authenticated/substituicoes'
import { Route as AuthenticatedSolicitacoesRouteImport } from './routes/_authenticated/solicitacoes'
import { Route as AuthenticatedSacristiaRouteImport } from './routes/_authenticated/sacristia'
import { Route as AuthenticatedRelatoriosSubstituicoesRouteImport } from './routes/_authenticated/relatorios-substituicoes'
import { Route as AuthenticatedRelatoriosEquilibrioRouteImport } from './routes/_authenticated/relatorios-equilibrio'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedPlanejamentoRouteImport } from './routes/_authenticated/planejamento'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedOcorrenciasRouteImport } from './routes/_authenticated/ocorrencias'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedMinisteriosRouteImport } from './routes/_authenticated/ministerios'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as AuthenticatedMembrosRouteImport } from './routes/_authenticated/membros'
import { Route as AuthenticatedFormacoesRouteImport } from './routes/_authenticated/formacoes'
import { Route as AuthenticatedEspiritualidadeRouteImport } from './routes/_authenticated/espiritualidade'
import { Route as AuthenticatedEscalasRouteImport } from './routes/_authenticated/escalas'
import { Route as AuthenticatedConfiguracoesEscalasRouteImport } from './routes/_authenticated/configuracoes-escalas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAjudaRouteImport } from './routes/_authenticated/ajuda'
import { Route as AuthenticatedConfiguracoesParoquiaRouteImport } from './routes/_authenticated/configuracoes.paroquia'
import { Route as AuthenticatedConfiguracoesAdministradoresRouteImport } from './routes/_authenticated/configuracoes.administradores'
import { Route as AuthenticatedAdminParoquiasRouteImport } from './routes/_authenticated/admin.paroquias'
import { Route as AuthenticatedAdminLiturgiaRouteImport } from './routes/_authenticated/admin.liturgia'

const ResetSenhaRoute = ResetSenhaRouteImport.update({
  id: '/reset-senha',
  path: '/reset-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMembroRoute = PortalMembroRouteImport.update({
  id: '/portal-membro',
  path: '/portal-membro',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoNegadoRoute = AcessoNegadoRouteImport.update({
  id: '/acesso-negado',
  path: '/acesso-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMembroSubstituicoesRoute =
  PortalMembroSubstituicoesRouteImport.update({
    id: '/substituicoes',
    path: '/substituicoes',
    getParentRoute: () => PortalMembroRoute,
  } as any)
const PortalMembroRankingRoute = PortalMembroRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => PortalMembroRoute,
} as any)
const PortalMembroPerfilRoute = PortalMembroPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PortalMembroRoute,
} as any)
const PortalMembroOcorrenciasRoute = PortalMembroOcorrenciasRouteImport.update({
  id: '/ocorrencias',
  path: '/ocorrencias',
  getParentRoute: () => PortalMembroRoute,
} as any)
const PortalMembroNotificacoesRoute =
  PortalMembroNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => PortalMembroRoute,
  } as any)
const PortalMembroLiturgiaRoute = PortalMembroLiturgiaRouteImport.update({
  id: '/liturgia',
  path: '/liturgia',
  getParentRoute: () => PortalMembroRoute,
} as any)
const PortalMembroHomeRoute = PortalMembroHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PortalMembroRoute,
} as any)
const PortalMembroEventosRoute = PortalMembroEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => PortalMembroRoute,
} as any)
const PortalMembroEscalasRoute = PortalMembroEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => PortalMembroRoute,
} as any)
const PortalMembroCompletarCadastroRoute =
  PortalMembroCompletarCadastroRouteImport.update({
    id: '/completar-cadastro',
    path: '/completar-cadastro',
    getParentRoute: () => PortalMembroRoute,
  } as any)
const PortalMembroCalendarioRoute = PortalMembroCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => PortalMembroRoute,
} as any)
const PortalMembroAjudaRoute = PortalMembroAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => PortalMembroRoute,
} as any)
const ParoquiaSlugRoute = ParoquiaSlugRouteImport.update({
  id: '/paroquia/$slug',
  path: '/paroquia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MembroPrimeiroAcessoRoute = MembroPrimeiroAcessoRouteImport.update({
  id: '/membro/primeiro-acesso',
  path: '/membro/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const MembroLoginRoute = MembroLoginRouteImport.update({
  id: '/membro/login',
  path: '/membro/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembroAtivarContaRoute = MembroAtivarContaRouteImport.update({
  id: '/membro/ativar-conta',
  path: '/membro/ativar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const MembroTokenRoute = MembroTokenRouteImport.update({
  id: '/membro/$token',
  path: '/membro/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoSlugRoute = InscricaoSlugRouteImport.update({
  id: '/inscricao/$slug',
  path: '/inscricao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalaTokenRoute = EscalaTokenRouteImport.update({
  id: '/escala/$token',
  path: '/escala/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMfaChallengeRoute = AuthMfaChallengeRouteImport.update({
  id: '/auth/mfa-challenge',
  path: '/auth/mfa-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminMfaRoute = AuthAdminMfaRouteImport.update({
  id: '/auth/admin-mfa',
  path: '/auth/admin-mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubstituicoesRoute =
  AuthenticatedSubstituicoesRouteImport.update({
    id: '/substituicoes',
    path: '/substituicoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSolicitacoesRoute =
  AuthenticatedSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSacristiaRoute = AuthenticatedSacristiaRouteImport.update({
  id: '/sacristia',
  path: '/sacristia',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosSubstituicoesRoute =
  AuthenticatedRelatoriosSubstituicoesRouteImport.update({
    id: '/relatorios-substituicoes',
    path: '/relatorios-substituicoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosEquilibrioRoute =
  AuthenticatedRelatoriosEquilibrioRouteImport.update({
    id: '/relatorios-equilibrio',
    path: '/relatorios-equilibrio',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanejamentoRoute =
  AuthenticatedPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOcorrenciasRoute =
  AuthenticatedOcorrenciasRouteImport.update({
    id: '/ocorrencias',
    path: '/ocorrencias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMinisteriosRoute =
  AuthenticatedMinisteriosRouteImport.update({
    id: '/ministerios',
    path: '/ministerios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembrosRoute = AuthenticatedMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormacoesRoute = AuthenticatedFormacoesRouteImport.update({
  id: '/formacoes',
  path: '/formacoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEspiritualidadeRoute =
  AuthenticatedEspiritualidadeRouteImport.update({
    id: '/espiritualidade',
    path: '/espiritualidade',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEscalasRoute = AuthenticatedEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesEscalasRoute =
  AuthenticatedConfiguracoesEscalasRouteImport.update({
    id: '/configuracoes-escalas',
    path: '/configuracoes-escalas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAjudaRoute = AuthenticatedAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesParoquiaRoute =
  AuthenticatedConfiguracoesParoquiaRouteImport.update({
    id: '/paroquia',
    path: '/paroquia',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesAdministradoresRoute =
  AuthenticatedConfiguracoesAdministradoresRouteImport.update({
    id: '/administradores',
    path: '/administradores',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedAdminParoquiasRoute =
  AuthenticatedAdminParoquiasRouteImport.update({
    id: '/admin/paroquias',
    path: '/admin/paroquias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLiturgiaRoute =
  AuthenticatedAdminLiturgiaRouteImport.update({
    id: '/admin/liturgia',
    path: '/admin/liturgia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/cadastro': typeof CadastroRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/portal-membro': typeof PortalMembroRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/configuracoes-escalas': typeof AuthenticatedConfiguracoesEscalasRoute
  '/escalas': typeof AuthenticatedEscalasRoute
  '/espiritualidade': typeof AuthenticatedEspiritualidadeRoute
  '/formacoes': typeof AuthenticatedFormacoesRoute
  '/membros': typeof AuthenticatedMembrosRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/ministerios': typeof AuthenticatedMinisteriosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios-equilibrio': typeof AuthenticatedRelatoriosEquilibrioRoute
  '/relatorios-substituicoes': typeof AuthenticatedRelatoriosSubstituicoesRoute
  '/sacristia': typeof AuthenticatedSacristiaRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/substituicoes': typeof AuthenticatedSubstituicoesRoute
  '/auth/admin-mfa': typeof AuthAdminMfaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/mfa-challenge': typeof AuthMfaChallengeRoute
  '/escala/$token': typeof EscalaTokenRoute
  '/inscricao/$slug': typeof InscricaoSlugRoute
  '/membro/$token': typeof MembroTokenRoute
  '/membro/ativar-conta': typeof MembroAtivarContaRoute
  '/membro/login': typeof MembroLoginRoute
  '/membro/primeiro-acesso': typeof MembroPrimeiroAcessoRoute
  '/paroquia/$slug': typeof ParoquiaSlugRoute
  '/portal-membro/ajuda': typeof PortalMembroAjudaRoute
  '/portal-membro/calendario': typeof PortalMembroCalendarioRoute
  '/portal-membro/completar-cadastro': typeof PortalMembroCompletarCadastroRoute
  '/portal-membro/escalas': typeof PortalMembroEscalasRoute
  '/portal-membro/eventos': typeof PortalMembroEventosRoute
  '/portal-membro/home': typeof PortalMembroHomeRoute
  '/portal-membro/liturgia': typeof PortalMembroLiturgiaRoute
  '/portal-membro/notificacoes': typeof PortalMembroNotificacoesRoute
  '/portal-membro/ocorrencias': typeof PortalMembroOcorrenciasRoute
  '/portal-membro/perfil': typeof PortalMembroPerfilRoute
  '/portal-membro/ranking': typeof PortalMembroRankingRoute
  '/portal-membro/substituicoes': typeof PortalMembroSubstituicoesRoute
  '/portal/$token': typeof PortalTokenRoute
  '/admin/liturgia': typeof AuthenticatedAdminLiturgiaRoute
  '/admin/paroquias': typeof AuthenticatedAdminParoquiasRoute
  '/configuracoes/administradores': typeof AuthenticatedConfiguracoesAdministradoresRoute
  '/configuracoes/paroquia': typeof AuthenticatedConfiguracoesParoquiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/cadastro': typeof CadastroRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/portal-membro': typeof PortalMembroRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/configuracoes-escalas': typeof AuthenticatedConfiguracoesEscalasRoute
  '/escalas': typeof AuthenticatedEscalasRoute
  '/espiritualidade': typeof AuthenticatedEspiritualidadeRoute
  '/formacoes': typeof AuthenticatedFormacoesRoute
  '/membros': typeof AuthenticatedMembrosRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/ministerios': typeof AuthenticatedMinisteriosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios-equilibrio': typeof AuthenticatedRelatoriosEquilibrioRoute
  '/relatorios-substituicoes': typeof AuthenticatedRelatoriosSubstituicoesRoute
  '/sacristia': typeof AuthenticatedSacristiaRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/substituicoes': typeof AuthenticatedSubstituicoesRoute
  '/auth/admin-mfa': typeof AuthAdminMfaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/mfa-challenge': typeof AuthMfaChallengeRoute
  '/escala/$token': typeof EscalaTokenRoute
  '/inscricao/$slug': typeof InscricaoSlugRoute
  '/membro/$token': typeof MembroTokenRoute
  '/membro/ativar-conta': typeof MembroAtivarContaRoute
  '/membro/login': typeof MembroLoginRoute
  '/membro/primeiro-acesso': typeof MembroPrimeiroAcessoRoute
  '/paroquia/$slug': typeof ParoquiaSlugRoute
  '/portal-membro/ajuda': typeof PortalMembroAjudaRoute
  '/portal-membro/calendario': typeof PortalMembroCalendarioRoute
  '/portal-membro/completar-cadastro': typeof PortalMembroCompletarCadastroRoute
  '/portal-membro/escalas': typeof PortalMembroEscalasRoute
  '/portal-membro/eventos': typeof PortalMembroEventosRoute
  '/portal-membro/home': typeof PortalMembroHomeRoute
  '/portal-membro/liturgia': typeof PortalMembroLiturgiaRoute
  '/portal-membro/notificacoes': typeof PortalMembroNotificacoesRoute
  '/portal-membro/ocorrencias': typeof PortalMembroOcorrenciasRoute
  '/portal-membro/perfil': typeof PortalMembroPerfilRoute
  '/portal-membro/ranking': typeof PortalMembroRankingRoute
  '/portal-membro/substituicoes': typeof PortalMembroSubstituicoesRoute
  '/portal/$token': typeof PortalTokenRoute
  '/admin/liturgia': typeof AuthenticatedAdminLiturgiaRoute
  '/admin/paroquias': typeof AuthenticatedAdminParoquiasRoute
  '/configuracoes/administradores': typeof AuthenticatedConfiguracoesAdministradoresRoute
  '/configuracoes/paroquia': typeof AuthenticatedConfiguracoesParoquiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/acesso-negado': typeof AcessoNegadoRoute
  '/cadastro': typeof CadastroRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/portal-membro': typeof PortalMembroRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/_authenticated/ajuda': typeof AuthenticatedAjudaRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/configuracoes-escalas': typeof AuthenticatedConfiguracoesEscalasRoute
  '/_authenticated/escalas': typeof AuthenticatedEscalasRoute
  '/_authenticated/espiritualidade': typeof AuthenticatedEspiritualidadeRoute
  '/_authenticated/formacoes': typeof AuthenticatedFormacoesRoute
  '/_authenticated/membros': typeof AuthenticatedMembrosRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/_authenticated/ministerios': typeof AuthenticatedMinisteriosRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/relatorios-equilibrio': typeof AuthenticatedRelatoriosEquilibrioRoute
  '/_authenticated/relatorios-substituicoes': typeof AuthenticatedRelatoriosSubstituicoesRoute
  '/_authenticated/sacristia': typeof AuthenticatedSacristiaRoute
  '/_authenticated/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/_authenticated/substituicoes': typeof AuthenticatedSubstituicoesRoute
  '/auth/admin-mfa': typeof AuthAdminMfaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/mfa-challenge': typeof AuthMfaChallengeRoute
  '/escala/$token': typeof EscalaTokenRoute
  '/inscricao/$slug': typeof InscricaoSlugRoute
  '/membro/$token': typeof MembroTokenRoute
  '/membro/ativar-conta': typeof MembroAtivarContaRoute
  '/membro/login': typeof MembroLoginRoute
  '/membro/primeiro-acesso': typeof MembroPrimeiroAcessoRoute
  '/paroquia/$slug': typeof ParoquiaSlugRoute
  '/portal-membro/ajuda': typeof PortalMembroAjudaRoute
  '/portal-membro/calendario': typeof PortalMembroCalendarioRoute
  '/portal-membro/completar-cadastro': typeof PortalMembroCompletarCadastroRoute
  '/portal-membro/escalas': typeof PortalMembroEscalasRoute
  '/portal-membro/eventos': typeof PortalMembroEventosRoute
  '/portal-membro/home': typeof PortalMembroHomeRoute
  '/portal-membro/liturgia': typeof PortalMembroLiturgiaRoute
  '/portal-membro/notificacoes': typeof PortalMembroNotificacoesRoute
  '/portal-membro/ocorrencias': typeof PortalMembroOcorrenciasRoute
  '/portal-membro/perfil': typeof PortalMembroPerfilRoute
  '/portal-membro/ranking': typeof PortalMembroRankingRoute
  '/portal-membro/substituicoes': typeof PortalMembroSubstituicoesRoute
  '/portal/$token': typeof PortalTokenRoute
  '/_authenticated/admin/liturgia': typeof AuthenticatedAdminLiturgiaRoute
  '/_authenticated/admin/paroquias': typeof AuthenticatedAdminParoquiasRoute
  '/_authenticated/configuracoes/administradores': typeof AuthenticatedConfiguracoesAdministradoresRoute
  '/_authenticated/configuracoes/paroquia': typeof AuthenticatedConfiguracoesParoquiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-negado'
    | '/cadastro'
    | '/esqueci-senha'
    | '/login'
    | '/onboarding'
    | '/portal-membro'
    | '/reset-senha'
    | '/ajuda'
    | '/auditoria'
    | '/calendario'
    | '/configuracoes'
    | '/configuracoes-escalas'
    | '/escalas'
    | '/espiritualidade'
    | '/formacoes'
    | '/membros'
    | '/minha-conta'
    | '/ministerios'
    | '/notificacoes'
    | '/ocorrencias'
    | '/painel'
    | '/planejamento'
    | '/ranking'
    | '/relatorios-equilibrio'
    | '/relatorios-substituicoes'
    | '/sacristia'
    | '/solicitacoes'
    | '/substituicoes'
    | '/auth/admin-mfa'
    | '/auth/callback'
    | '/auth/mfa-challenge'
    | '/escala/$token'
    | '/inscricao/$slug'
    | '/membro/$token'
    | '/membro/ativar-conta'
    | '/membro/login'
    | '/membro/primeiro-acesso'
    | '/paroquia/$slug'
    | '/portal-membro/ajuda'
    | '/portal-membro/calendario'
    | '/portal-membro/completar-cadastro'
    | '/portal-membro/escalas'
    | '/portal-membro/eventos'
    | '/portal-membro/home'
    | '/portal-membro/liturgia'
    | '/portal-membro/notificacoes'
    | '/portal-membro/ocorrencias'
    | '/portal-membro/perfil'
    | '/portal-membro/ranking'
    | '/portal-membro/substituicoes'
    | '/portal/$token'
    | '/admin/liturgia'
    | '/admin/paroquias'
    | '/configuracoes/administradores'
    | '/configuracoes/paroquia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-negado'
    | '/cadastro'
    | '/esqueci-senha'
    | '/login'
    | '/onboarding'
    | '/portal-membro'
    | '/reset-senha'
    | '/ajuda'
    | '/auditoria'
    | '/calendario'
    | '/configuracoes'
    | '/configuracoes-escalas'
    | '/escalas'
    | '/espiritualidade'
    | '/formacoes'
    | '/membros'
    | '/minha-conta'
    | '/ministerios'
    | '/notificacoes'
    | '/ocorrencias'
    | '/painel'
    | '/planejamento'
    | '/ranking'
    | '/relatorios-equilibrio'
    | '/relatorios-substituicoes'
    | '/sacristia'
    | '/solicitacoes'
    | '/substituicoes'
    | '/auth/admin-mfa'
    | '/auth/callback'
    | '/auth/mfa-challenge'
    | '/escala/$token'
    | '/inscricao/$slug'
    | '/membro/$token'
    | '/membro/ativar-conta'
    | '/membro/login'
    | '/membro/primeiro-acesso'
    | '/paroquia/$slug'
    | '/portal-membro/ajuda'
    | '/portal-membro/calendario'
    | '/portal-membro/completar-cadastro'
    | '/portal-membro/escalas'
    | '/portal-membro/eventos'
    | '/portal-membro/home'
    | '/portal-membro/liturgia'
    | '/portal-membro/notificacoes'
    | '/portal-membro/ocorrencias'
    | '/portal-membro/perfil'
    | '/portal-membro/ranking'
    | '/portal-membro/substituicoes'
    | '/portal/$token'
    | '/admin/liturgia'
    | '/admin/paroquias'
    | '/configuracoes/administradores'
    | '/configuracoes/paroquia'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acesso-negado'
    | '/cadastro'
    | '/esqueci-senha'
    | '/login'
    | '/onboarding'
    | '/portal-membro'
    | '/reset-senha'
    | '/_authenticated/ajuda'
    | '/_authenticated/auditoria'
    | '/_authenticated/calendario'
    | '/_authenticated/configuracoes'
    | '/_authenticated/configuracoes-escalas'
    | '/_authenticated/escalas'
    | '/_authenticated/espiritualidade'
    | '/_authenticated/formacoes'
    | '/_authenticated/membros'
    | '/_authenticated/minha-conta'
    | '/_authenticated/ministerios'
    | '/_authenticated/notificacoes'
    | '/_authenticated/ocorrencias'
    | '/_authenticated/painel'
    | '/_authenticated/planejamento'
    | '/_authenticated/ranking'
    | '/_authenticated/relatorios-equilibrio'
    | '/_authenticated/relatorios-substituicoes'
    | '/_authenticated/sacristia'
    | '/_authenticated/solicitacoes'
    | '/_authenticated/substituicoes'
    | '/auth/admin-mfa'
    | '/auth/callback'
    | '/auth/mfa-challenge'
    | '/escala/$token'
    | '/inscricao/$slug'
    | '/membro/$token'
    | '/membro/ativar-conta'
    | '/membro/login'
    | '/membro/primeiro-acesso'
    | '/paroquia/$slug'
    | '/portal-membro/ajuda'
    | '/portal-membro/calendario'
    | '/portal-membro/completar-cadastro'
    | '/portal-membro/escalas'
    | '/portal-membro/eventos'
    | '/portal-membro/home'
    | '/portal-membro/liturgia'
    | '/portal-membro/notificacoes'
    | '/portal-membro/ocorrencias'
    | '/portal-membro/perfil'
    | '/portal-membro/ranking'
    | '/portal-membro/substituicoes'
    | '/portal/$token'
    | '/_authenticated/admin/liturgia'
    | '/_authenticated/admin/paroquias'
    | '/_authenticated/configuracoes/administradores'
    | '/_authenticated/configuracoes/paroquia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcessoNegadoRoute: typeof AcessoNegadoRoute
  CadastroRoute: typeof CadastroRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PortalMembroRoute: typeof PortalMembroRouteWithChildren
  ResetSenhaRoute: typeof ResetSenhaRoute
  AuthAdminMfaRoute: typeof AuthAdminMfaRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthMfaChallengeRoute: typeof AuthMfaChallengeRoute
  EscalaTokenRoute: typeof EscalaTokenRoute
  InscricaoSlugRoute: typeof InscricaoSlugRoute
  MembroTokenRoute: typeof MembroTokenRoute
  MembroAtivarContaRoute: typeof MembroAtivarContaRoute
  MembroLoginRoute: typeof MembroLoginRoute
  MembroPrimeiroAcessoRoute: typeof MembroPrimeiroAcessoRoute
  ParoquiaSlugRoute: typeof ParoquiaSlugRoute
  PortalTokenRoute: typeof PortalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-senha': {
      id: '/reset-senha'
      path: '/reset-senha'
      fullPath: '/reset-senha'
      preLoaderRoute: typeof ResetSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-membro': {
      id: '/portal-membro'
      path: '/portal-membro'
      fullPath: '/portal-membro'
      preLoaderRoute: typeof PortalMembroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-negado': {
      id: '/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof AcessoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-membro/substituicoes': {
      id: '/portal-membro/substituicoes'
      path: '/substituicoes'
      fullPath: '/portal-membro/substituicoes'
      preLoaderRoute: typeof PortalMembroSubstituicoesRouteImport
      parentRoute: typeof PortalMembroRoute
    }
    '/portal-membro/ranking': {
      id: '/portal-membro/ranking'
      path: '/ranking'
      fullPath: '/portal-membro/ranking'
      preLoaderRoute: typeof PortalMembroRankingRouteImport
      parentRoute: typeof PortalMembroRoute
    }
    '/portal-membro/perfil': {
      id: '/portal-membro/perfil'
      path: '/perfil'
      fullPath: '/portal-membro/perfil'
      preLoaderRoute: typeof PortalMembroPerfilRouteImport
      parentRoute: typeof PortalMembroRoute
    }
    '/portal-membro/ocorrencias': {
      id: '/portal-membro/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/portal-membro/ocorrencias'
      preLoaderRoute: typeof PortalMembroOcorrenciasRouteImport
      parentRoute: typeof PortalMembroRoute
    }
    '/portal-membro/notificacoes': {
      id: '/portal-membro/notificacoes'
      path: '/notificacoes'
      fullPath: '/portal-membro/notificacoes'
      preLoaderRoute: typeof PortalMembroNotificacoesRouteImport
      parentRoute: typeof PortalMembroRoute
    }
    '/portal-membro/liturgia': {
      id: '/portal-membro/liturgia'
      path: '/liturgia'
      fullPath: '/portal-membro/liturgia'
      preLoaderRoute: typeof PortalMembroLiturgiaRouteImport
      parentRoute: typeof PortalMembroRoute
    }
    '/portal-membro/home': {
      id: '/portal-membro/home'
      path: '/home'
      fullPath: '/portal-membro/home'
      preLoaderRoute: typeof PortalMembroHomeRouteImport
      parentRoute: typeof PortalMembroRoute
    }
    '/portal-membro/eventos': {
      id: '/portal-membro/eventos'
      path: '/eventos'
      fullPath: '/portal-membro/eventos'
      preLoaderRoute: typeof PortalMembroEventosRouteImport
      parentRoute: typeof PortalMembroRoute
    }
    '/portal-membro/escalas': {
      id: '/portal-membro/escalas'
      path: '/escalas'
      fullPath: '/portal-membro/escalas'
      preLoaderRoute: typeof PortalMembroEscalasRouteImport
      parentRoute: typeof PortalMembroRoute
    }
    '/portal-membro/completar-cadastro': {
      id: '/portal-membro/completar-cadastro'
      path: '/completar-cadastro'
      fullPath: '/portal-membro/completar-cadastro'
      preLoaderRoute: typeof PortalMembroCompletarCadastroRouteImport
      parentRoute: typeof PortalMembroRoute
    }
    '/portal-membro/calendario': {
      id: '/portal-membro/calendario'
      path: '/calendario'
      fullPath: '/portal-membro/calendario'
      preLoaderRoute: typeof PortalMembroCalendarioRouteImport
      parentRoute: typeof PortalMembroRoute
    }
    '/portal-membro/ajuda': {
      id: '/portal-membro/ajuda'
      path: '/ajuda'
      fullPath: '/portal-membro/ajuda'
      preLoaderRoute: typeof PortalMembroAjudaRouteImport
      parentRoute: typeof PortalMembroRoute
    }
    '/paroquia/$slug': {
      id: '/paroquia/$slug'
      path: '/paroquia/$slug'
      fullPath: '/paroquia/$slug'
      preLoaderRoute: typeof ParoquiaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membro/primeiro-acesso': {
      id: '/membro/primeiro-acesso'
      path: '/membro/primeiro-acesso'
      fullPath: '/membro/primeiro-acesso'
      preLoaderRoute: typeof MembroPrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membro/login': {
      id: '/membro/login'
      path: '/membro/login'
      fullPath: '/membro/login'
      preLoaderRoute: typeof MembroLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membro/ativar-conta': {
      id: '/membro/ativar-conta'
      path: '/membro/ativar-conta'
      fullPath: '/membro/ativar-conta'
      preLoaderRoute: typeof MembroAtivarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membro/$token': {
      id: '/membro/$token'
      path: '/membro/$token'
      fullPath: '/membro/$token'
      preLoaderRoute: typeof MembroTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/$slug': {
      id: '/inscricao/$slug'
      path: '/inscricao/$slug'
      fullPath: '/inscricao/$slug'
      preLoaderRoute: typeof InscricaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escala/$token': {
      id: '/escala/$token'
      path: '/escala/$token'
      fullPath: '/escala/$token'
      preLoaderRoute: typeof EscalaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa-challenge': {
      id: '/auth/mfa-challenge'
      path: '/auth/mfa-challenge'
      fullPath: '/auth/mfa-challenge'
      preLoaderRoute: typeof AuthMfaChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin-mfa': {
      id: '/auth/admin-mfa'
      path: '/auth/admin-mfa'
      fullPath: '/auth/admin-mfa'
      preLoaderRoute: typeof AuthAdminMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/substituicoes': {
      id: '/_authenticated/substituicoes'
      path: '/substituicoes'
      fullPath: '/substituicoes'
      preLoaderRoute: typeof AuthenticatedSubstituicoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/solicitacoes': {
      id: '/_authenticated/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof AuthenticatedSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sacristia': {
      id: '/_authenticated/sacristia'
      path: '/sacristia'
      fullPath: '/sacristia'
      preLoaderRoute: typeof AuthenticatedSacristiaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios-substituicoes': {
      id: '/_authenticated/relatorios-substituicoes'
      path: '/relatorios-substituicoes'
      fullPath: '/relatorios-substituicoes'
      preLoaderRoute: typeof AuthenticatedRelatoriosSubstituicoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios-equilibrio': {
      id: '/_authenticated/relatorios-equilibrio'
      path: '/relatorios-equilibrio'
      fullPath: '/relatorios-equilibrio'
      preLoaderRoute: typeof AuthenticatedRelatoriosEquilibrioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planejamento': {
      id: '/_authenticated/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AuthenticatedPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ocorrencias': {
      id: '/_authenticated/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/ocorrencias'
      preLoaderRoute: typeof AuthenticatedOcorrenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ministerios': {
      id: '/_authenticated/ministerios'
      path: '/ministerios'
      fullPath: '/ministerios'
      preLoaderRoute: typeof AuthenticatedMinisteriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membros': {
      id: '/_authenticated/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof AuthenticatedMembrosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formacoes': {
      id: '/_authenticated/formacoes'
      path: '/formacoes'
      fullPath: '/formacoes'
      preLoaderRoute: typeof AuthenticatedFormacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/espiritualidade': {
      id: '/_authenticated/espiritualidade'
      path: '/espiritualidade'
      fullPath: '/espiritualidade'
      preLoaderRoute: typeof AuthenticatedEspiritualidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/escalas': {
      id: '/_authenticated/escalas'
      path: '/escalas'
      fullPath: '/escalas'
      preLoaderRoute: typeof AuthenticatedEscalasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes-escalas': {
      id: '/_authenticated/configuracoes-escalas'
      path: '/configuracoes-escalas'
      fullPath: '/configuracoes-escalas'
      preLoaderRoute: typeof AuthenticatedConfiguracoesEscalasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ajuda': {
      id: '/_authenticated/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AuthenticatedAjudaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes/paroquia': {
      id: '/_authenticated/configuracoes/paroquia'
      path: '/paroquia'
      fullPath: '/configuracoes/paroquia'
      preLoaderRoute: typeof AuthenticatedConfiguracoesParoquiaRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/administradores': {
      id: '/_authenticated/configuracoes/administradores'
      path: '/administradores'
      fullPath: '/configuracoes/administradores'
      preLoaderRoute: typeof AuthenticatedConfiguracoesAdministradoresRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/admin/paroquias': {
      id: '/_authenticated/admin/paroquias'
      path: '/admin/paroquias'
      fullPath: '/admin/paroquias'
      preLoaderRoute: typeof AuthenticatedAdminParoquiasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/liturgia': {
      id: '/_authenticated/admin/liturgia'
      path: '/admin/liturgia'
      fullPath: '/admin/liturgia'
      preLoaderRoute: typeof AuthenticatedAdminLiturgiaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesAdministradoresRoute: typeof AuthenticatedConfiguracoesAdministradoresRoute
  AuthenticatedConfiguracoesParoquiaRoute: typeof AuthenticatedConfiguracoesParoquiaRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesAdministradoresRoute:
      AuthenticatedConfiguracoesAdministradoresRoute,
    AuthenticatedConfiguracoesParoquiaRoute:
      AuthenticatedConfiguracoesParoquiaRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAjudaRoute: typeof AuthenticatedAjudaRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedConfiguracoesEscalasRoute: typeof AuthenticatedConfiguracoesEscalasRoute
  AuthenticatedEscalasRoute: typeof AuthenticatedEscalasRoute
  AuthenticatedEspiritualidadeRoute: typeof AuthenticatedEspiritualidadeRoute
  AuthenticatedFormacoesRoute: typeof AuthenticatedFormacoesRoute
  AuthenticatedMembrosRoute: typeof AuthenticatedMembrosRoute
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
  AuthenticatedMinisteriosRoute: typeof AuthenticatedMinisteriosRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedOcorrenciasRoute: typeof AuthenticatedOcorrenciasRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPlanejamentoRoute: typeof AuthenticatedPlanejamentoRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRelatoriosEquilibrioRoute: typeof AuthenticatedRelatoriosEquilibrioRoute
  AuthenticatedRelatoriosSubstituicoesRoute: typeof AuthenticatedRelatoriosSubstituicoesRoute
  AuthenticatedSacristiaRoute: typeof AuthenticatedSacristiaRoute
  AuthenticatedSolicitacoesRoute: typeof AuthenticatedSolicitacoesRoute
  AuthenticatedSubstituicoesRoute: typeof AuthenticatedSubstituicoesRoute
  AuthenticatedAdminLiturgiaRoute: typeof AuthenticatedAdminLiturgiaRoute
  AuthenticatedAdminParoquiasRoute: typeof AuthenticatedAdminParoquiasRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAjudaRoute: AuthenticatedAjudaRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedConfiguracoesEscalasRoute:
    AuthenticatedConfiguracoesEscalasRoute,
  AuthenticatedEscalasRoute: AuthenticatedEscalasRoute,
  AuthenticatedEspiritualidadeRoute: AuthenticatedEspiritualidadeRoute,
  AuthenticatedFormacoesRoute: AuthenticatedFormacoesRoute,
  AuthenticatedMembrosRoute: AuthenticatedMembrosRoute,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
  AuthenticatedMinisteriosRoute: AuthenticatedMinisteriosRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedOcorrenciasRoute: AuthenticatedOcorrenciasRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPlanejamentoRoute: AuthenticatedPlanejamentoRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRelatoriosEquilibrioRoute:
    AuthenticatedRelatoriosEquilibrioRoute,
  AuthenticatedRelatoriosSubstituicoesRoute:
    AuthenticatedRelatoriosSubstituicoesRoute,
  AuthenticatedSacristiaRoute: AuthenticatedSacristiaRoute,
  AuthenticatedSolicitacoesRoute: AuthenticatedSolicitacoesRoute,
  AuthenticatedSubstituicoesRoute: AuthenticatedSubstituicoesRoute,
  AuthenticatedAdminLiturgiaRoute: AuthenticatedAdminLiturgiaRoute,
  AuthenticatedAdminParoquiasRoute: AuthenticatedAdminParoquiasRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortalMembroRouteChildren {
  PortalMembroAjudaRoute: typeof PortalMembroAjudaRoute
  PortalMembroCalendarioRoute: typeof PortalMembroCalendarioRoute
  PortalMembroCompletarCadastroRoute: typeof PortalMembroCompletarCadastroRoute
  PortalMembroEscalasRoute: typeof PortalMembroEscalasRoute
  PortalMembroEventosRoute: typeof PortalMembroEventosRoute
  PortalMembroHomeRoute: typeof PortalMembroHomeRoute
  PortalMembroLiturgiaRoute: typeof PortalMembroLiturgiaRoute
  PortalMembroNotificacoesRoute: typeof PortalMembroNotificacoesRoute
  PortalMembroOcorrenciasRoute: typeof PortalMembroOcorrenciasRoute
  PortalMembroPerfilRoute: typeof PortalMembroPerfilRoute
  PortalMembroRankingRoute: typeof PortalMembroRankingRoute
  PortalMembroSubstituicoesRoute: typeof PortalMembroSubstituicoesRoute
}

const PortalMembroRouteChildren: PortalMembroRouteChildren = {
  PortalMembroAjudaRoute: PortalMembroAjudaRoute,
  PortalMembroCalendarioRoute: PortalMembroCalendarioRoute,
  PortalMembroCompletarCadastroRoute: PortalMembroCompletarCadastroRoute,
  PortalMembroEscalasRoute: PortalMembroEscalasRoute,
  PortalMembroEventosRoute: PortalMembroEventosRoute,
  PortalMembroHomeRoute: PortalMembroHomeRoute,
  PortalMembroLiturgiaRoute: PortalMembroLiturgiaRoute,
  PortalMembroNotificacoesRoute: PortalMembroNotificacoesRoute,
  PortalMembroOcorrenciasRoute: PortalMembroOcorrenciasRoute,
  PortalMembroPerfilRoute: PortalMembroPerfilRoute,
  PortalMembroRankingRoute: PortalMembroRankingRoute,
  PortalMembroSubstituicoesRoute: PortalMembroSubstituicoesRoute,
}

const PortalMembroRouteWithChildren = PortalMembroRoute._addFileChildren(
  PortalMembroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcessoNegadoRoute: AcessoNegadoRoute,
  CadastroRoute: CadastroRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PortalMembroRoute: PortalMembroRouteWithChildren,
  ResetSenhaRoute: ResetSenhaRoute,
  AuthAdminMfaRoute: AuthAdminMfaRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthMfaChallengeRoute: AuthMfaChallengeRoute,
  EscalaTokenRoute: EscalaTokenRoute,
  InscricaoSlugRoute: InscricaoSlugRoute,
  MembroTokenRoute: MembroTokenRoute,
  MembroAtivarContaRoute: MembroAtivarContaRoute,
  MembroLoginRoute: MembroLoginRoute,
  MembroPrimeiroAcessoRoute: MembroPrimeiroAcessoRoute,
  ParoquiaSlugRoute: ParoquiaSlugRoute,
  PortalTokenRoute: PortalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
